In [51]:
import numpy as np
import pandas as pd

In [52]:
df = pd.DataFrame()

In [53]:
level_of_education = ['Senior Secondary']*30 + ['Bachelors']*30

In [54]:
level_of_education

['Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Senior Secondary',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors',
 'Bachelors']

In [55]:
teaching_methodology = ['Theory']*20 + ['Hands On']*20 + ['Combination']*20

In [56]:
teaching_methodology

['Theory',
 'Theory',
 'Theory',
 'Theory',
 'Theory',
 'Theory',
 'Theory',
 'Theory',
 'Theory',
 'Theory',
 'Theory',
 'Theory',
 'Theory',
 'Theory',
 'Theory',
 'Theory',
 'Theory',
 'Theory',
 'Theory',
 'Theory',
 'Hands On',
 'Hands On',
 'Hands On',
 'Hands On',
 'Hands On',
 'Hands On',
 'Hands On',
 'Hands On',
 'Hands On',
 'Hands On',
 'Hands On',
 'Hands On',
 'Hands On',
 'Hands On',
 'Hands On',
 'Hands On',
 'Hands On',
 'Hands On',
 'Hands On',
 'Hands On',
 'Combination',
 'Combination',
 'Combination',
 'Combination',
 'Combination',
 'Combination',
 'Combination',
 'Combination',
 'Combination',
 'Combination',
 'Combination',
 'Combination',
 'Combination',
 'Combination',
 'Combination',
 'Combination',
 'Combination',
 'Combination',
 'Combination',
 'Combination']

In [57]:
ss_theory = np.random.normal(loc=34, scale=2, size=10)

ss_handson = np.random.normal(loc=45, scale=4, size=10)

ss_combination = np.random.normal(loc=51, scale=3.5, size=10)

bachelors_theory = np.random.normal(loc=30, scale=1.5, size=10)

bachelors_handson = np.random.normal(loc=55, scale=6, size=10)

bachelors_combination = np.random.normal(loc=48, scale=2.5, size=10)

attention_span = np.concatenate((ss_theory, ss_handson, ss_combination, bachelors_theory, bachelors_handson, bachelors_combination))

In [58]:
attention_span

array([30.35815197, 33.05579983, 33.5172091 , 36.03989084, 36.97267325,
       32.52080615, 32.55274266, 34.58834919, 36.18204077, 33.9298632 ,
       40.86705982, 38.399373  , 44.13335748, 48.48476688, 44.35569934,
       46.29755182, 42.74328374, 45.39331422, 46.08627079, 40.13568228,
       52.93930024, 52.34354254, 57.90627929, 54.19410169, 50.83842315,
       53.09831226, 45.56916493, 55.56466622, 51.21557106, 58.9524457 ,
       28.03573876, 29.98415068, 29.5432277 , 31.22009928, 28.70862875,
       30.1987885 , 29.69409693, 29.80035068, 32.04153024, 30.59560154,
       53.11713726, 50.94570302, 49.37554531, 49.42269112, 54.13368886,
       49.02190706, 52.59516893, 51.7470668 , 58.36637203, 70.74540359,
       48.72047541, 48.63443586, 44.22408206, 46.88160836, 48.33868138,
       46.16620942, 47.79061999, 50.03783897, 45.59718522, 44.54835384])

In [59]:
df['LE'] = level_of_education

df['TM'] = teaching_methodology

df['AS'] = attention_span

In [60]:
df

                  LE           TM         AS
0   Senior Secondary       Theory  30.358152
1   Senior Secondary       Theory  33.055800
2   Senior Secondary       Theory  33.517209
3   Senior Secondary       Theory  36.039891
4   Senior Secondary       Theory  36.972673
5   Senior Secondary       Theory  32.520806
6   Senior Secondary       Theory  32.552743
7   Senior Secondary       Theory  34.588349
8   Senior Secondary       Theory  36.182041
9   Senior Secondary       Theory  33.929863
10  Senior Secondary       Theory  40.867060
11  Senior Secondary       Theory  38.399373
12  Senior Secondary       Theory  44.133357
13  Senior Secondary       Theory  48.484767
14  Senior Secondary       Theory  44.355699
15  Senior Secondary       Theory  46.297552
16  Senior Secondary       Theory  42.743284
17  Senior Secondary       Theory  45.393314
18  Senior Secondary       Theory  46.086271
19  Senior Secondary       Theory  40.135682
20  Senior Secondary     Hands On  52.939300
21  Senior Secondary     Hands On  52.343543
22  Senior Secondary     Hands On  57.906279
23  Senior Secondary     Hands On  54.194102
24  Senior Secondary     Hands On  50.838423
25  Senior Secondary     Hands On  53.098312
26  Senior Secondary     Hands On  45.569165
27  Senior Secondary     Hands On  55.564666
28  Senior Secondary     Hands On  51.215571
29  Senior Secondary     Hands On  58.952446
30         Bachelors     Hands On  28.035739
31         Bachelors     Hands On  29.984151
32         Bachelors     Hands On  29.543228
33         Bachelors     Hands On  31.220099
34         Bachelors     Hands On  28.708629
35         Bachelors     Hands On  30.198788
36         Bachelors     Hands On  29.694097
37         Bachelors     Hands On  29.800351
38         Bachelors     Hands On  32.041530
39         Bachelors     Hands On  30.595602
40         Bachelors  Combination  53.117137
41         Bachelors  Combination  50.945703
42         Bachelors  Combination  49.375545
43         Bachelors  Combination  49.422691
44         Bachelors  Combination  54.133689
45         Bachelors  Combination  49.021907
46         Bachelors  Combination  52.595169
47         Bachelors  Combination  51.747067
48         Bachelors  Combination  58.366372
49         Bachelors  Combination  70.745404
50         Bachelors  Combination  48.720475
51         Bachelors  Combination  48.634436
52         Bachelors  Combination  44.224082
53         Bachelors  Combination  46.881608
54         Bachelors  Combination  48.338681
55         Bachelors  Combination  46.166209
56         Bachelors  Combination  47.790620
57         Bachelors  Combination  50.037839
58         Bachelors  Combination  45.597185
59         Bachelors  Combination  44.548354

In [68]:
import statsmodels.api as sm

In [69]:
from statsmodels.formula.api import ols

In [70]:
model = ols(formula='AS ~ C(LE) + C(TM) + (C(LE)*C(TM))', data=df).fit()

In [71]:
sm.stats.annova_lm(model, typ=2)

AttributeError: module 'statsmodels.stats.api' has no attribute 'annova_lm'